changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - deps
        - ci
        - dependencies
    - title: Other Changes
      labels:
        - "*"
