#!/usr/bin/env node
// Generates Sources/MaskinDesign/Generated/Tokens.swift from the v2 design
// tokens in .claude/skills/maskin-design/tokens/*.css — the same files the web
// app's look is specified against. Never edit the generated file by hand:
// change a token in the CSS, re-run this script.
//
//   node apps/apple/scripts/gen-tokens.mjs           # write
//   node apps/apple/scripts/gen-tokens.mjs --check   # exit 1 if the file is stale (CI)
//
// Status/type badge pairs come from apps/web/src/app.css.
//
// Scope: tokens a native client can use as-is — colors (light + dark), radii,
// spacing, type sizes and motion durations. Shadows, easings, clamp()/min()
// layout values and font stacks are intentionally skipped; they are expressed
// in code in MaskinDesign.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const tokensDir = resolve(here, '../../../.claude/skills/maskin-design/tokens')
const outFile = resolve(here, '../Sources/MaskinDesign/Generated/Tokens.swift')

const read = (name) =>
	readFileSync(resolve(tokensDir, name), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')

/** Innermost `selector { body }` blocks → [{ selector, props: Map }]. */
function blocks(css) {
	const out = []
	for (const m of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
		const props = new Map()
		for (const p of m[2].matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) props.set(p[1], p[2].trim())
		out.push({ selector: m[1].trim(), props })
	}
	return out
}

const light = (css) => blocks(css).find((b) => b.selector === ':root')?.props ?? new Map()
const dark = (css) => blocks(css).find((b) => b.selector.includes('html.dark'))?.props ?? new Map()

const camel = (s) => s.replace(/-+([a-z0-9])/g, (_, c) => c.toUpperCase())

/** `#rgb`, `#rrggbb` or `rgba(r, g, b, a)` → Swift `RGBA(...)`; null if not a color. */
function swiftColor(v) {
	let m = v.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i)
	if (m) {
		const h = m[1].length === 3 ? [...m[1]].map((c) => c + c).join('') : m[1]
		return `RGBA(0x${h.toUpperCase()})`
	}
	m = v.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/i)
	if (m) {
		const alpha = m[4] === undefined ? 1 : Number(m[4])
		return `RGBA(red: ${m[1]}, green: ${m[2]}, blue: ${m[3]}, alpha: ${alpha})`
	}
	return null
}

const num = (v, unit) => {
	const m = v.match(new RegExp(`^(-?[\\d.]+)${unit}$`))
	return m ? Number(m[1]) : null
}

const lines = []
const emit = (s = '') => lines.push(s)

emit('// GENERATED by apps/apple/scripts/gen-tokens.mjs — DO NOT EDIT.')
emit(
	'// Source: .claude/skills/maskin-design/tokens/*.css, apps/web/src/app.css (status/type pairs)',
)
emit()
emit('import SwiftUI')
emit()

// --- colors ---------------------------------------------------------------
const colorsCss = read('colors.css')
const colorsLight = light(colorsCss)
const colorsDark = dark(colorsCss)
emit('/// Semantic colors. Names mirror the CSS custom properties (`--ink-2` → `ink2`).')
emit('/// Each adapts to the system appearance; the dark values come from the token')
emit("/// file's `html.dark` swap, and a token with no dark override is the same in both.")
emit('public enum MaskinColor {')
for (const [name, value] of colorsLight) {
	const l = swiftColor(value)
	if (!l) continue // shadows etc.
	const d = swiftColor(colorsDark.get(name) ?? value)
	emit(`\tpublic static let ${camel(name.slice(2))} = Color(light: ${l}, dark: ${d})`)
}
emit('}')
emit()

// --- radii ----------------------------------------------------------------
const shapeLight = light(read('shape.css'))
emit('/// Corner radii in points, by intent (`--r-card` → `card`).')
emit('public enum MaskinRadius {')
for (const [name, value] of shapeLight) {
	if (!name.startsWith('--r-')) continue
	const px = num(value, 'px')
	if (px !== null) emit(`\tpublic static let ${camel(name.slice(4))}: CGFloat = ${px}`)
}
emit('}')
emit()

// --- spacing --------------------------------------------------------------
const spacingLight = light(read('spacing.css'))
emit('/// Spacing scale in points (`--space-7` → `s7`, `--gap-loose` → `gapLoose`).')
emit('public enum MaskinSpace {')
for (const [name, value] of spacingLight) {
	const px = value === '0' ? 0 : num(value, 'px')
	if (px === null) continue
	if (name.startsWith('--space-')) emit(`\tpublic static let s${name.slice(8)}: CGFloat = ${px}`)
	else if (name.startsWith('--gap-'))
		emit(`\tpublic static let ${camel(name.slice(2))}: CGFloat = ${px}`)
	else if (name === '--touch-min') emit(`\tpublic static let touchMin: CGFloat = ${px}`)
}
emit('}')
emit()

// --- type sizes -----------------------------------------------------------
const typeLight = light(read('typography.css'))
emit('/// Font sizes in points (`--text-13-5` → `t13_5`).')
emit('public enum MaskinFontSize {')
for (const [name, value] of typeLight) {
	if (!name.startsWith('--text-')) continue
	const px = num(value, 'px')
	if (px !== null) emit(`\tpublic static let t${name.slice(7).replace('-', '_')}: CGFloat = ${px}`)
}
emit('}')
emit()

// --- motion ---------------------------------------------------------------
const motionLight = light(read('motion.css'))
emit('/// Durations in seconds (`--dur-150` → `d150`, `--dur-slide` → `slide`).')
emit('public enum MaskinDuration {')
for (const [name, value] of motionLight) {
	if (!name.startsWith('--dur-')) continue
	const ms = num(value, 'ms')
	if (ms !== null) {
		const key = /^\d/.test(name.slice(6)) ? `d${name.slice(6)}` : camel(name.slice(6))
		emit(`\tpublic static let ${key}: Double = ${ms / 1000}`)
	}
}
emit('}')

// --- status + type badge pairs ---------------------------------------------
// These live in apps/web/src/app.css (`--st-*`, `--tp-*`), not in the skill token
// files: the web app is the source of truth for badge colours. Light is `:root`,
// dark is the `.dark` block.
const appCss = readFileSync(resolve(here, '../../web/src/app.css'), 'utf8').replace(
	/\/\*[\s\S]*?\*\//g,
	'',
)
const appBlocks = blocks(appCss)
const appLight = appBlocks.find((b) => b.selector === ':root')?.props ?? new Map()
const appDark = appBlocks.find((b) => b.selector === '.dark')?.props ?? new Map()

function pairs(prefix, textSuffix) {
	const keys = []
	for (const name of appLight.keys()) {
		const m = name.match(new RegExp(`^--${prefix}-(.+)-bg$`))
		if (m && appLight.has(`--${prefix}-${m[1]}-${textSuffix}`)) keys.push(m[1])
	}
	return keys
}

function emitPairs(enumName, doc, prefix) {
	emit(doc)
	emit(`public enum ${enumName} {`)
	emit('	public static let all: [String: MaskinColorPair] = [')
	for (const key of pairs(prefix, 'text')) {
		const col = (suffix) => {
			const name = `--${prefix}-${key}-${suffix}`
			const l = swiftColor(appLight.get(name))
			const d = swiftColor(appDark.get(name) ?? appLight.get(name))
			return `Color(light: ${l}, dark: ${d})`
		}
		emit(`		"${key}": MaskinColorPair(bg: ${col('bg')}, fg: ${col('text')}),`)
	}
	emit('	]')
	emit('}')
	emit()
}

emit()
emitPairs(
	'MaskinStatusPalette',
	'/// Status badge colours keyed by the CSS token key (`--st-in_progress-*` → `"in_progress"`).',
	'st',
)
emitPairs(
	'MaskinTypePalette',
	'/// Object-type badge colours keyed by the CSS token key (`--tp-insight-*` → `"insight"`).',
	'tp',
)

const generated = `${lines.join('\n')}\n`

if (process.argv.includes('--check')) {
	const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : ''
	if (current !== generated) {
		console.error('Tokens.swift is stale — run: node apps/apple/scripts/gen-tokens.mjs')
		process.exit(1)
	}
	console.log('Tokens.swift is up to date')
} else {
	mkdirSync(dirname(outFile), { recursive: true })
	writeFileSync(outFile, generated)
	console.log(`Wrote ${outFile} (${lines.length} lines)`)
}
