// Config for the 17 single-agent Development-workspace catalog packages.
// Each entry publishes one live actor (plus every trigger whose targetActorId
// is that actor) from the Development workspace
// (fe944fe6-7b45-478c-afc7-b889cea63c08) as its own installable package.
//
// Developer + Code Reviewer are published here individually *and* as part of
// the Development Pipeline bundle (./dev-pipeline-package.ts); the three CCD
// actors (Customer Feedback Agent, Insights Triage Agent, Product Ideator) are
// published here *and* in the Customer Continuous Discovery bundle
// (./ccd-package.ts). Both read the same checked-in snapshot data, so there is
// no duplication of source content — just different catalog groupings of it.
//
// Actor/trigger content is sourced from data/dev-actors.json + data/dev-triggers.json
// (see ./package-data), captured live because the local dev Postgres is empty.
//
// Exported so the publish script and its tests can share the exact same shape.

import {
	CCD_ACTOR_CUSTOMER_FEEDBACK,
	CCD_ACTOR_INSIGHTS_TRIAGE,
	CCD_ACTOR_PRODUCT_IDEATOR,
	DEV_ACTOR_ARCHITECT,
	DEV_ACTOR_CODE_REVIEWER,
	DEV_ACTOR_DESIGNER,
	DEV_ACTOR_DEVELOPER,
	DEV_ACTOR_PLANNER,
	DEV_ACTOR_PRODUCT_ANALYST,
	DEV_ACTOR_PRODUCT_MARKETER,
	DEV_ACTOR_PRODUCT_PRICING_SPECIALIST,
	DEV_ACTOR_RESEARCH_AGENT,
	DEV_ACTOR_RETRO_KNOWLEDGE_AUTHOR,
	DEV_ACTOR_STRATEGIST,
	DEV_ACTOR_SUMMARIZATION_AGENT,
	DEV_ACTOR_WORKSPACE_COACH,
	DEV_ACTOR_WORKSPACE_DRIVER,
	DEV_PACKAGE_ARCHITECT_DESCRIPTION,
	DEV_PACKAGE_ARCHITECT_NAME,
	DEV_PACKAGE_ARCHITECT_SLUG,
	DEV_PACKAGE_CODE_REVIEWER_DESCRIPTION,
	DEV_PACKAGE_CODE_REVIEWER_NAME,
	DEV_PACKAGE_CODE_REVIEWER_SLUG,
	DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_DESCRIPTION,
	DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_NAME,
	DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_SLUG,
	DEV_PACKAGE_DESIGNER_DESCRIPTION,
	DEV_PACKAGE_DESIGNER_NAME,
	DEV_PACKAGE_DESIGNER_SLUG,
	DEV_PACKAGE_DEVELOPER_DESCRIPTION,
	DEV_PACKAGE_DEVELOPER_NAME,
	DEV_PACKAGE_DEVELOPER_SLUG,
	DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_DESCRIPTION,
	DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_NAME,
	DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_SLUG,
	DEV_PACKAGE_PLANNER_DESCRIPTION,
	DEV_PACKAGE_PLANNER_NAME,
	DEV_PACKAGE_PLANNER_SLUG,
	DEV_PACKAGE_PRODUCT_ANALYST_DESCRIPTION,
	DEV_PACKAGE_PRODUCT_ANALYST_NAME,
	DEV_PACKAGE_PRODUCT_ANALYST_SLUG,
	DEV_PACKAGE_PRODUCT_IDEATOR_DESCRIPTION,
	DEV_PACKAGE_PRODUCT_IDEATOR_NAME,
	DEV_PACKAGE_PRODUCT_IDEATOR_SLUG,
	DEV_PACKAGE_PRODUCT_MARKETER_DESCRIPTION,
	DEV_PACKAGE_PRODUCT_MARKETER_NAME,
	DEV_PACKAGE_PRODUCT_MARKETER_SLUG,
	DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_DESCRIPTION,
	DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_NAME,
	DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_SLUG,
	DEV_PACKAGE_RESEARCH_AGENT_DESCRIPTION,
	DEV_PACKAGE_RESEARCH_AGENT_NAME,
	DEV_PACKAGE_RESEARCH_AGENT_SLUG,
	DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_DESCRIPTION,
	DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_NAME,
	DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_SLUG,
	DEV_PACKAGE_STRATEGIST_DESCRIPTION,
	DEV_PACKAGE_STRATEGIST_NAME,
	DEV_PACKAGE_STRATEGIST_SLUG,
	DEV_PACKAGE_SUMMARIZATION_AGENT_DESCRIPTION,
	DEV_PACKAGE_SUMMARIZATION_AGENT_NAME,
	DEV_PACKAGE_SUMMARIZATION_AGENT_SLUG,
	DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	DEV_PACKAGE_USE_CASE_DISCOVERY,
	DEV_PACKAGE_USE_CASE_GROWTH,
	DEV_PACKAGE_USE_CASE_OPERATIONS,
	DEV_PACKAGE_VERSION,
	DEV_PACKAGE_WORKSPACE_COACH_DESCRIPTION,
	DEV_PACKAGE_WORKSPACE_COACH_NAME,
	DEV_PACKAGE_WORKSPACE_COACH_SLUG,
	DEV_PACKAGE_WORKSPACE_DRIVER_DESCRIPTION,
	DEV_PACKAGE_WORKSPACE_DRIVER_NAME,
	DEV_PACKAGE_WORKSPACE_DRIVER_SLUG,
} from '@maskin/shared'
import { skillIdsForActor, triggerIdsForActor } from './package-data'

export { actorSnapshot, skillSnapshot, triggerSnapshot } from './package-snapshot'

export const DEV_AGENT_PACKAGES_SOURCE_WORKSPACE_ID = 'fe944fe6-7b45-478c-afc7-b889cea63c08'

export interface DevAgentPackageConfig {
	package: {
		slug: string
		name: string
		version: string
		useCase: string
		description: string
	}
	actorIds: readonly string[]
	triggerIds: readonly string[]
	skillIds: readonly string[]
}

function singleAgentPackage(
	slug: string,
	name: string,
	description: string,
	actorId: string,
	useCase: string,
): DevAgentPackageConfig {
	return {
		package: {
			slug,
			name,
			version: DEV_PACKAGE_VERSION,
			useCase,
			description,
		},
		actorIds: [actorId],
		triggerIds: triggerIdsForActor(actorId),
		skillIds: skillIdsForActor(actorId),
	}
}

export const DEV_AGENT_PACKAGES: readonly DevAgentPackageConfig[] = [
	// Build & Ship — bet definition through PR merge.
	singleAgentPackage(
		DEV_PACKAGE_PLANNER_SLUG,
		DEV_PACKAGE_PLANNER_NAME,
		DEV_PACKAGE_PLANNER_DESCRIPTION,
		DEV_ACTOR_PLANNER,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	singleAgentPackage(
		DEV_PACKAGE_DEVELOPER_SLUG,
		DEV_PACKAGE_DEVELOPER_NAME,
		DEV_PACKAGE_DEVELOPER_DESCRIPTION,
		DEV_ACTOR_DEVELOPER,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	singleAgentPackage(
		DEV_PACKAGE_ARCHITECT_SLUG,
		DEV_PACKAGE_ARCHITECT_NAME,
		DEV_PACKAGE_ARCHITECT_DESCRIPTION,
		DEV_ACTOR_ARCHITECT,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	singleAgentPackage(
		DEV_PACKAGE_DESIGNER_SLUG,
		DEV_PACKAGE_DESIGNER_NAME,
		DEV_PACKAGE_DESIGNER_DESCRIPTION,
		DEV_ACTOR_DESIGNER,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	singleAgentPackage(
		DEV_PACKAGE_CODE_REVIEWER_SLUG,
		DEV_PACKAGE_CODE_REVIEWER_NAME,
		DEV_PACKAGE_CODE_REVIEWER_DESCRIPTION,
		DEV_ACTOR_CODE_REVIEWER,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	singleAgentPackage(
		DEV_PACKAGE_WORKSPACE_DRIVER_SLUG,
		DEV_PACKAGE_WORKSPACE_DRIVER_NAME,
		DEV_PACKAGE_WORKSPACE_DRIVER_DESCRIPTION,
		DEV_ACTOR_WORKSPACE_DRIVER,
		DEV_PACKAGE_USE_CASE_DEVELOPMENT,
	),
	// Discover & Research — raw signal (feedback, meetings, external research) into insights/bet candidates.
	singleAgentPackage(
		DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_SLUG,
		DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_NAME,
		DEV_PACKAGE_CUSTOMER_FEEDBACK_AGENT_DESCRIPTION,
		CCD_ACTOR_CUSTOMER_FEEDBACK,
		DEV_PACKAGE_USE_CASE_DISCOVERY,
	),
	singleAgentPackage(
		DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_SLUG,
		DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_NAME,
		DEV_PACKAGE_INSIGHTS_TRIAGE_AGENT_DESCRIPTION,
		CCD_ACTOR_INSIGHTS_TRIAGE,
		DEV_PACKAGE_USE_CASE_DISCOVERY,
	),
	singleAgentPackage(
		DEV_PACKAGE_PRODUCT_IDEATOR_SLUG,
		DEV_PACKAGE_PRODUCT_IDEATOR_NAME,
		DEV_PACKAGE_PRODUCT_IDEATOR_DESCRIPTION,
		CCD_ACTOR_PRODUCT_IDEATOR,
		DEV_PACKAGE_USE_CASE_DISCOVERY,
	),
	singleAgentPackage(
		DEV_PACKAGE_RESEARCH_AGENT_SLUG,
		DEV_PACKAGE_RESEARCH_AGENT_NAME,
		DEV_PACKAGE_RESEARCH_AGENT_DESCRIPTION,
		DEV_ACTOR_RESEARCH_AGENT,
		DEV_PACKAGE_USE_CASE_DISCOVERY,
	),
	singleAgentPackage(
		DEV_PACKAGE_SUMMARIZATION_AGENT_SLUG,
		DEV_PACKAGE_SUMMARIZATION_AGENT_NAME,
		DEV_PACKAGE_SUMMARIZATION_AGENT_DESCRIPTION,
		DEV_ACTOR_SUMMARIZATION_AGENT,
		DEV_PACKAGE_USE_CASE_DISCOVERY,
	),
	// Strategy & Growth — decide what to build, measure live bets, price and market it.
	singleAgentPackage(
		DEV_PACKAGE_STRATEGIST_SLUG,
		DEV_PACKAGE_STRATEGIST_NAME,
		DEV_PACKAGE_STRATEGIST_DESCRIPTION,
		DEV_ACTOR_STRATEGIST,
		DEV_PACKAGE_USE_CASE_GROWTH,
	),
	singleAgentPackage(
		DEV_PACKAGE_PRODUCT_ANALYST_SLUG,
		DEV_PACKAGE_PRODUCT_ANALYST_NAME,
		DEV_PACKAGE_PRODUCT_ANALYST_DESCRIPTION,
		DEV_ACTOR_PRODUCT_ANALYST,
		DEV_PACKAGE_USE_CASE_GROWTH,
	),
	singleAgentPackage(
		DEV_PACKAGE_PRODUCT_MARKETER_SLUG,
		DEV_PACKAGE_PRODUCT_MARKETER_NAME,
		DEV_PACKAGE_PRODUCT_MARKETER_DESCRIPTION,
		DEV_ACTOR_PRODUCT_MARKETER,
		DEV_PACKAGE_USE_CASE_GROWTH,
	),
	singleAgentPackage(
		DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_SLUG,
		DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_NAME,
		DEV_PACKAGE_PRODUCT_PRICING_SPECIALIST_DESCRIPTION,
		DEV_ACTOR_PRODUCT_PRICING_SPECIALIST,
		DEV_PACKAGE_USE_CASE_GROWTH,
	),
	// Team Ops & Retro — looks backward at how the team/agents performed.
	singleAgentPackage(
		DEV_PACKAGE_WORKSPACE_COACH_SLUG,
		DEV_PACKAGE_WORKSPACE_COACH_NAME,
		DEV_PACKAGE_WORKSPACE_COACH_DESCRIPTION,
		DEV_ACTOR_WORKSPACE_COACH,
		DEV_PACKAGE_USE_CASE_OPERATIONS,
	),
	singleAgentPackage(
		DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_SLUG,
		DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_NAME,
		DEV_PACKAGE_RETRO_KNOWLEDGE_AUTHOR_DESCRIPTION,
		DEV_ACTOR_RETRO_KNOWLEDGE_AUTHOR,
		DEV_PACKAGE_USE_CASE_OPERATIONS,
	),
] as const
