/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as PrototypesAboveTitleHeaderRouteImport } from './routes/prototypes/above-title-header'
import { Route as AuthedWorkspacesRouteImport } from './routes/_authed/workspaces'
import { Route as AuthedWorkspaceIdRouteImport } from './routes/_authed/$workspaceId'
import { Route as AuthedWorkspaceIdIndexRouteImport } from './routes/_authed/$workspaceId/index'
import { Route as AuthedWorkspaceIdSettingsRouteImport } from './routes/_authed/$workspaceId/settings'
import { Route as AuthedWorkspaceIdMarketplaceRouteImport } from './routes/_authed/$workspaceId/marketplace'
import { Route as AuthedWorkspaceIdBriefingRouteImport } from './routes/_authed/$workspaceId/briefing'
import { Route as AuthedWorkspaceIdActivityRouteImport } from './routes/_authed/$workspaceId/activity'
import { Route as AuthedWorkspaceIdTriggersIndexRouteImport } from './routes/_authed/$workspaceId/triggers/index'
import { Route as AuthedWorkspaceIdSettingsIndexRouteImport } from './routes/_authed/$workspaceId/settings/index'
import { Route as AuthedWorkspaceIdObjectsIndexRouteImport } from './routes/_authed/$workspaceId/objects/index'
import { Route as AuthedWorkspaceIdAgentsIndexRouteImport } from './routes/_authed/$workspaceId/agents/index'
import { Route as AuthedWorkspaceIdTriggersTriggerIdRouteImport } from './routes/_authed/$workspaceId/triggers/$triggerId'
import { Route as AuthedWorkspaceIdSettingsSkillsRouteImport } from './routes/_authed/$workspaceId/settings/skills'
import { Route as AuthedWorkspaceIdSettingsMembersRouteImport } from './routes/_authed/$workspaceId/settings/members'
import { Route as AuthedWorkspaceIdSettingsMcpRouteImport } from './routes/_authed/$workspaceId/settings/mcp'
import { Route as AuthedWorkspaceIdSettingsKeysRouteImport } from './routes/_authed/$workspaceId/settings/keys'
import { Route as AuthedWorkspaceIdSettingsIntegrationsRouteImport } from './routes/_authed/$workspaceId/settings/integrations'
import { Route as AuthedWorkspaceIdObjectsObjectIdRouteImport } from './routes/_authed/$workspaceId/objects/$objectId'
import { Route as AuthedWorkspaceIdFilesFileIdRouteImport } from './routes/_authed/$workspaceId/files/$fileId'
import { Route as AuthedWorkspaceIdAgentsAgentIdRouteImport } from './routes/_authed/$workspaceId/agents/$agentId'
import { Route as AuthedWorkspaceIdSettingsObjectsIndexRouteImport } from './routes/_authed/$workspaceId/settings/objects/index'
import { Route as AuthedWorkspaceIdSettingsObjectsPropertyNameRouteImport } from './routes/_authed/$workspaceId/settings/objects/$propertyName'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const PrototypesAboveTitleHeaderRoute =
  PrototypesAboveTitleHeaderRouteImport.update({
    id: '/prototypes/above-title-header',
    path: '/prototypes/above-title-header',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedWorkspacesRoute = AuthedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceIdRoute = AuthedWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceIdIndexRoute = AuthedWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWorkspaceIdRoute,
} as any)
const AuthedWorkspaceIdSettingsRoute =
  AuthedWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdMarketplaceRoute =
  AuthedWorkspaceIdMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdBriefingRoute =
  AuthedWorkspaceIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdActivityRoute =
  AuthedWorkspaceIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdTriggersIndexRoute =
  AuthedWorkspaceIdTriggersIndexRouteImport.update({
    id: '/triggers/',
    path: '/triggers/',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdSettingsIndexRoute =
  AuthedWorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdObjectsIndexRoute =
  AuthedWorkspaceIdObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdAgentsIndexRoute =
  AuthedWorkspaceIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdTriggersTriggerIdRoute =
  AuthedWorkspaceIdTriggersTriggerIdRouteImport.update({
    id: '/triggers/$triggerId',
    path: '/triggers/$triggerId',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdSettingsSkillsRoute =
  AuthedWorkspaceIdSettingsSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdSettingsMembersRoute =
  AuthedWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdSettingsMcpRoute =
  AuthedWorkspaceIdSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdSettingsKeysRoute =
  AuthedWorkspaceIdSettingsKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdSettingsIntegrationsRoute =
  AuthedWorkspaceIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdObjectsObjectIdRoute =
  AuthedWorkspaceIdObjectsObjectIdRouteImport.update({
    id: '/objects/$objectId',
    path: '/objects/$objectId',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdFilesFileIdRoute =
  AuthedWorkspaceIdFilesFileIdRouteImport.update({
    id: '/files/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdAgentsAgentIdRoute =
  AuthedWorkspaceIdAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthedWorkspaceIdRoute,
  } as any)
const AuthedWorkspaceIdSettingsObjectsIndexRoute =
  AuthedWorkspaceIdSettingsObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)
const AuthedWorkspaceIdSettingsObjectsPropertyNameRoute =
  AuthedWorkspaceIdSettingsObjectsPropertyNameRouteImport.update({
    id: '/objects/$propertyName',
    path: '/objects/$propertyName',
    getParentRoute: () => AuthedWorkspaceIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$workspaceId': typeof AuthedWorkspaceIdRouteWithChildren
  '/workspaces': typeof AuthedWorkspacesRoute
  '/prototypes/above-title-header': typeof PrototypesAboveTitleHeaderRoute
  '/$workspaceId/activity': typeof AuthedWorkspaceIdActivityRoute
  '/$workspaceId/briefing': typeof AuthedWorkspaceIdBriefingRoute
  '/$workspaceId/marketplace': typeof AuthedWorkspaceIdMarketplaceRoute
  '/$workspaceId/settings': typeof AuthedWorkspaceIdSettingsRouteWithChildren
  '/$workspaceId/': typeof AuthedWorkspaceIdIndexRoute
  '/$workspaceId/agents/$agentId': typeof AuthedWorkspaceIdAgentsAgentIdRoute
  '/$workspaceId/files/$fileId': typeof AuthedWorkspaceIdFilesFileIdRoute
  '/$workspaceId/objects/$objectId': typeof AuthedWorkspaceIdObjectsObjectIdRoute
  '/$workspaceId/settings/integrations': typeof AuthedWorkspaceIdSettingsIntegrationsRoute
  '/$workspaceId/settings/keys': typeof AuthedWorkspaceIdSettingsKeysRoute
  '/$workspaceId/settings/mcp': typeof AuthedWorkspaceIdSettingsMcpRoute
  '/$workspaceId/settings/members': typeof AuthedWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/skills': typeof AuthedWorkspaceIdSettingsSkillsRoute
  '/$workspaceId/triggers/$triggerId': typeof AuthedWorkspaceIdTriggersTriggerIdRoute
  '/$workspaceId/agents/': typeof AuthedWorkspaceIdAgentsIndexRoute
  '/$workspaceId/objects/': typeof AuthedWorkspaceIdObjectsIndexRoute
  '/$workspaceId/settings/': typeof AuthedWorkspaceIdSettingsIndexRoute
  '/$workspaceId/triggers/': typeof AuthedWorkspaceIdTriggersIndexRoute
  '/$workspaceId/settings/objects/$propertyName': typeof AuthedWorkspaceIdSettingsObjectsPropertyNameRoute
  '/$workspaceId/settings/objects/': typeof AuthedWorkspaceIdSettingsObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof AuthedWorkspacesRoute
  '/prototypes/above-title-header': typeof PrototypesAboveTitleHeaderRoute
  '/': typeof AuthedIndexRoute
  '/$workspaceId/activity': typeof AuthedWorkspaceIdActivityRoute
  '/$workspaceId/briefing': typeof AuthedWorkspaceIdBriefingRoute
  '/$workspaceId/marketplace': typeof AuthedWorkspaceIdMarketplaceRoute
  '/$workspaceId': typeof AuthedWorkspaceIdIndexRoute
  '/$workspaceId/agents/$agentId': typeof AuthedWorkspaceIdAgentsAgentIdRoute
  '/$workspaceId/files/$fileId': typeof AuthedWorkspaceIdFilesFileIdRoute
  '/$workspaceId/objects/$objectId': typeof AuthedWorkspaceIdObjectsObjectIdRoute
  '/$workspaceId/settings/integrations': typeof AuthedWorkspaceIdSettingsIntegrationsRoute
  '/$workspaceId/settings/keys': typeof AuthedWorkspaceIdSettingsKeysRoute
  '/$workspaceId/settings/mcp': typeof AuthedWorkspaceIdSettingsMcpRoute
  '/$workspaceId/settings/members': typeof AuthedWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/skills': typeof AuthedWorkspaceIdSettingsSkillsRoute
  '/$workspaceId/triggers/$triggerId': typeof AuthedWorkspaceIdTriggersTriggerIdRoute
  '/$workspaceId/agents': typeof AuthedWorkspaceIdAgentsIndexRoute
  '/$workspaceId/objects': typeof AuthedWorkspaceIdObjectsIndexRoute
  '/$workspaceId/settings': typeof AuthedWorkspaceIdSettingsIndexRoute
  '/$workspaceId/triggers': typeof AuthedWorkspaceIdTriggersIndexRoute
  '/$workspaceId/settings/objects/$propertyName': typeof AuthedWorkspaceIdSettingsObjectsPropertyNameRoute
  '/$workspaceId/settings/objects': typeof AuthedWorkspaceIdSettingsObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/$workspaceId': typeof AuthedWorkspaceIdRouteWithChildren
  '/_authed/workspaces': typeof AuthedWorkspacesRoute
  '/prototypes/above-title-header': typeof PrototypesAboveTitleHeaderRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$workspaceId/activity': typeof AuthedWorkspaceIdActivityRoute
  '/_authed/$workspaceId/briefing': typeof AuthedWorkspaceIdBriefingRoute
  '/_authed/$workspaceId/marketplace': typeof AuthedWorkspaceIdMarketplaceRoute
  '/_authed/$workspaceId/settings': typeof AuthedWorkspaceIdSettingsRouteWithChildren
  '/_authed/$workspaceId/': typeof AuthedWorkspaceIdIndexRoute
  '/_authed/$workspaceId/agents/$agentId': typeof AuthedWorkspaceIdAgentsAgentIdRoute
  '/_authed/$workspaceId/files/$fileId': typeof AuthedWorkspaceIdFilesFileIdRoute
  '/_authed/$workspaceId/objects/$objectId': typeof AuthedWorkspaceIdObjectsObjectIdRoute
  '/_authed/$workspaceId/settings/integrations': typeof AuthedWorkspaceIdSettingsIntegrationsRoute
  '/_authed/$workspaceId/settings/keys': typeof AuthedWorkspaceIdSettingsKeysRoute
  '/_authed/$workspaceId/settings/mcp': typeof AuthedWorkspaceIdSettingsMcpRoute
  '/_authed/$workspaceId/settings/members': typeof AuthedWorkspaceIdSettingsMembersRoute
  '/_authed/$workspaceId/settings/skills': typeof AuthedWorkspaceIdSettingsSkillsRoute
  '/_authed/$workspaceId/triggers/$triggerId': typeof AuthedWorkspaceIdTriggersTriggerIdRoute
  '/_authed/$workspaceId/agents/': typeof AuthedWorkspaceIdAgentsIndexRoute
  '/_authed/$workspaceId/objects/': typeof AuthedWorkspaceIdObjectsIndexRoute
  '/_authed/$workspaceId/settings/': typeof AuthedWorkspaceIdSettingsIndexRoute
  '/_authed/$workspaceId/triggers/': typeof AuthedWorkspaceIdTriggersIndexRoute
  '/_authed/$workspaceId/settings/objects/$propertyName': typeof AuthedWorkspaceIdSettingsObjectsPropertyNameRoute
  '/_authed/$workspaceId/settings/objects/': typeof AuthedWorkspaceIdSettingsObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/$workspaceId'
    | '/workspaces'
    | '/prototypes/above-title-header'
    | '/$workspaceId/activity'
    | '/$workspaceId/briefing'
    | '/$workspaceId/marketplace'
    | '/$workspaceId/settings'
    | '/$workspaceId/'
    | '/$workspaceId/agents/$agentId'
    | '/$workspaceId/files/$fileId'
    | '/$workspaceId/objects/$objectId'
    | '/$workspaceId/settings/integrations'
    | '/$workspaceId/settings/keys'
    | '/$workspaceId/settings/mcp'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/skills'
    | '/$workspaceId/triggers/$triggerId'
    | '/$workspaceId/agents/'
    | '/$workspaceId/objects/'
    | '/$workspaceId/settings/'
    | '/$workspaceId/triggers/'
    | '/$workspaceId/settings/objects/$propertyName'
    | '/$workspaceId/settings/objects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/workspaces'
    | '/prototypes/above-title-header'
    | '/'
    | '/$workspaceId/activity'
    | '/$workspaceId/briefing'
    | '/$workspaceId/marketplace'
    | '/$workspaceId'
    | '/$workspaceId/agents/$agentId'
    | '/$workspaceId/files/$fileId'
    | '/$workspaceId/objects/$objectId'
    | '/$workspaceId/settings/integrations'
    | '/$workspaceId/settings/keys'
    | '/$workspaceId/settings/mcp'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/skills'
    | '/$workspaceId/triggers/$triggerId'
    | '/$workspaceId/agents'
    | '/$workspaceId/objects'
    | '/$workspaceId/settings'
    | '/$workspaceId/triggers'
    | '/$workspaceId/settings/objects/$propertyName'
    | '/$workspaceId/settings/objects'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/$workspaceId'
    | '/_authed/workspaces'
    | '/prototypes/above-title-header'
    | '/_authed/'
    | '/_authed/$workspaceId/activity'
    | '/_authed/$workspaceId/briefing'
    | '/_authed/$workspaceId/marketplace'
    | '/_authed/$workspaceId/settings'
    | '/_authed/$workspaceId/'
    | '/_authed/$workspaceId/agents/$agentId'
    | '/_authed/$workspaceId/files/$fileId'
    | '/_authed/$workspaceId/objects/$objectId'
    | '/_authed/$workspaceId/settings/integrations'
    | '/_authed/$workspaceId/settings/keys'
    | '/_authed/$workspaceId/settings/mcp'
    | '/_authed/$workspaceId/settings/members'
    | '/_authed/$workspaceId/settings/skills'
    | '/_authed/$workspaceId/triggers/$triggerId'
    | '/_authed/$workspaceId/agents/'
    | '/_authed/$workspaceId/objects/'
    | '/_authed/$workspaceId/settings/'
    | '/_authed/$workspaceId/triggers/'
    | '/_authed/$workspaceId/settings/objects/$propertyName'
    | '/_authed/$workspaceId/settings/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PrototypesAboveTitleHeaderRoute: typeof PrototypesAboveTitleHeaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/prototypes/above-title-header': {
      id: '/prototypes/above-title-header'
      path: '/prototypes/above-title-header'
      fullPath: '/prototypes/above-title-header'
      preLoaderRoute: typeof PrototypesAboveTitleHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workspaces': {
      id: '/_authed/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthedWorkspacesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceId': {
      id: '/_authed/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof AuthedWorkspaceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceId/': {
      id: '/_authed/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof AuthedWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/settings': {
      id: '/_authed/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/marketplace': {
      id: '/_authed/$workspaceId/marketplace'
      path: '/marketplace'
      fullPath: '/$workspaceId/marketplace'
      preLoaderRoute: typeof AuthedWorkspaceIdMarketplaceRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/briefing': {
      id: '/_authed/$workspaceId/briefing'
      path: '/briefing'
      fullPath: '/$workspaceId/briefing'
      preLoaderRoute: typeof AuthedWorkspaceIdBriefingRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/activity': {
      id: '/_authed/$workspaceId/activity'
      path: '/activity'
      fullPath: '/$workspaceId/activity'
      preLoaderRoute: typeof AuthedWorkspaceIdActivityRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/triggers/': {
      id: '/_authed/$workspaceId/triggers/'
      path: '/triggers'
      fullPath: '/$workspaceId/triggers/'
      preLoaderRoute: typeof AuthedWorkspaceIdTriggersIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/settings/': {
      id: '/_authed/$workspaceId/settings/'
      path: '/'
      fullPath: '/$workspaceId/settings/'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/objects/': {
      id: '/_authed/$workspaceId/objects/'
      path: '/objects'
      fullPath: '/$workspaceId/objects/'
      preLoaderRoute: typeof AuthedWorkspaceIdObjectsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/agents/': {
      id: '/_authed/$workspaceId/agents/'
      path: '/agents'
      fullPath: '/$workspaceId/agents/'
      preLoaderRoute: typeof AuthedWorkspaceIdAgentsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/triggers/$triggerId': {
      id: '/_authed/$workspaceId/triggers/$triggerId'
      path: '/triggers/$triggerId'
      fullPath: '/$workspaceId/triggers/$triggerId'
      preLoaderRoute: typeof AuthedWorkspaceIdTriggersTriggerIdRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/settings/skills': {
      id: '/_authed/$workspaceId/settings/skills'
      path: '/skills'
      fullPath: '/$workspaceId/settings/skills'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsSkillsRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/settings/members': {
      id: '/_authed/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/$workspaceId/settings/members'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/settings/mcp': {
      id: '/_authed/$workspaceId/settings/mcp'
      path: '/mcp'
      fullPath: '/$workspaceId/settings/mcp'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsMcpRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/settings/keys': {
      id: '/_authed/$workspaceId/settings/keys'
      path: '/keys'
      fullPath: '/$workspaceId/settings/keys'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsKeysRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/settings/integrations': {
      id: '/_authed/$workspaceId/settings/integrations'
      path: '/integrations'
      fullPath: '/$workspaceId/settings/integrations'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/objects/$objectId': {
      id: '/_authed/$workspaceId/objects/$objectId'
      path: '/objects/$objectId'
      fullPath: '/$workspaceId/objects/$objectId'
      preLoaderRoute: typeof AuthedWorkspaceIdObjectsObjectIdRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/files/$fileId': {
      id: '/_authed/$workspaceId/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/$workspaceId/files/$fileId'
      preLoaderRoute: typeof AuthedWorkspaceIdFilesFileIdRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/agents/$agentId': {
      id: '/_authed/$workspaceId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/$workspaceId/agents/$agentId'
      preLoaderRoute: typeof AuthedWorkspaceIdAgentsAgentIdRouteImport
      parentRoute: typeof AuthedWorkspaceIdRoute
    }
    '/_authed/$workspaceId/settings/objects/': {
      id: '/_authed/$workspaceId/settings/objects/'
      path: '/objects'
      fullPath: '/$workspaceId/settings/objects/'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsObjectsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
    '/_authed/$workspaceId/settings/objects/$propertyName': {
      id: '/_authed/$workspaceId/settings/objects/$propertyName'
      path: '/objects/$propertyName'
      fullPath: '/$workspaceId/settings/objects/$propertyName'
      preLoaderRoute: typeof AuthedWorkspaceIdSettingsObjectsPropertyNameRouteImport
      parentRoute: typeof AuthedWorkspaceIdSettingsRoute
    }
  }
}

interface AuthedWorkspaceIdSettingsRouteChildren {
  AuthedWorkspaceIdSettingsIntegrationsRoute: typeof AuthedWorkspaceIdSettingsIntegrationsRoute
  AuthedWorkspaceIdSettingsKeysRoute: typeof AuthedWorkspaceIdSettingsKeysRoute
  AuthedWorkspaceIdSettingsMcpRoute: typeof AuthedWorkspaceIdSettingsMcpRoute
  AuthedWorkspaceIdSettingsMembersRoute: typeof AuthedWorkspaceIdSettingsMembersRoute
  AuthedWorkspaceIdSettingsSkillsRoute: typeof AuthedWorkspaceIdSettingsSkillsRoute
  AuthedWorkspaceIdSettingsIndexRoute: typeof AuthedWorkspaceIdSettingsIndexRoute
  AuthedWorkspaceIdSettingsObjectsPropertyNameRoute: typeof AuthedWorkspaceIdSettingsObjectsPropertyNameRoute
  AuthedWorkspaceIdSettingsObjectsIndexRoute: typeof AuthedWorkspaceIdSettingsObjectsIndexRoute
}

const AuthedWorkspaceIdSettingsRouteChildren: AuthedWorkspaceIdSettingsRouteChildren =
  {
    AuthedWorkspaceIdSettingsIntegrationsRoute:
      AuthedWorkspaceIdSettingsIntegrationsRoute,
    AuthedWorkspaceIdSettingsKeysRoute: AuthedWorkspaceIdSettingsKeysRoute,
    AuthedWorkspaceIdSettingsMcpRoute: AuthedWorkspaceIdSettingsMcpRoute,
    AuthedWorkspaceIdSettingsMembersRoute:
      AuthedWorkspaceIdSettingsMembersRoute,
    AuthedWorkspaceIdSettingsSkillsRoute: AuthedWorkspaceIdSettingsSkillsRoute,
    AuthedWorkspaceIdSettingsIndexRoute: AuthedWorkspaceIdSettingsIndexRoute,
    AuthedWorkspaceIdSettingsObjectsPropertyNameRoute:
      AuthedWorkspaceIdSettingsObjectsPropertyNameRoute,
    AuthedWorkspaceIdSettingsObjectsIndexRoute:
      AuthedWorkspaceIdSettingsObjectsIndexRoute,
  }

const AuthedWorkspaceIdSettingsRouteWithChildren =
  AuthedWorkspaceIdSettingsRoute._addFileChildren(
    AuthedWorkspaceIdSettingsRouteChildren,
  )

interface AuthedWorkspaceIdRouteChildren {
  AuthedWorkspaceIdActivityRoute: typeof AuthedWorkspaceIdActivityRoute
  AuthedWorkspaceIdBriefingRoute: typeof AuthedWorkspaceIdBriefingRoute
  AuthedWorkspaceIdMarketplaceRoute: typeof AuthedWorkspaceIdMarketplaceRoute
  AuthedWorkspaceIdSettingsRoute: typeof AuthedWorkspaceIdSettingsRouteWithChildren
  AuthedWorkspaceIdIndexRoute: typeof AuthedWorkspaceIdIndexRoute
  AuthedWorkspaceIdAgentsAgentIdRoute: typeof AuthedWorkspaceIdAgentsAgentIdRoute
  AuthedWorkspaceIdFilesFileIdRoute: typeof AuthedWorkspaceIdFilesFileIdRoute
  AuthedWorkspaceIdObjectsObjectIdRoute: typeof AuthedWorkspaceIdObjectsObjectIdRoute
  AuthedWorkspaceIdTriggersTriggerIdRoute: typeof AuthedWorkspaceIdTriggersTriggerIdRoute
  AuthedWorkspaceIdAgentsIndexRoute: typeof AuthedWorkspaceIdAgentsIndexRoute
  AuthedWorkspaceIdObjectsIndexRoute: typeof AuthedWorkspaceIdObjectsIndexRoute
  AuthedWorkspaceIdTriggersIndexRoute: typeof AuthedWorkspaceIdTriggersIndexRoute
}

const AuthedWorkspaceIdRouteChildren: AuthedWorkspaceIdRouteChildren = {
  AuthedWorkspaceIdActivityRoute: AuthedWorkspaceIdActivityRoute,
  AuthedWorkspaceIdBriefingRoute: AuthedWorkspaceIdBriefingRoute,
  AuthedWorkspaceIdMarketplaceRoute: AuthedWorkspaceIdMarketplaceRoute,
  AuthedWorkspaceIdSettingsRoute: AuthedWorkspaceIdSettingsRouteWithChildren,
  AuthedWorkspaceIdIndexRoute: AuthedWorkspaceIdIndexRoute,
  AuthedWorkspaceIdAgentsAgentIdRoute: AuthedWorkspaceIdAgentsAgentIdRoute,
  AuthedWorkspaceIdFilesFileIdRoute: AuthedWorkspaceIdFilesFileIdRoute,
  AuthedWorkspaceIdObjectsObjectIdRoute: AuthedWorkspaceIdObjectsObjectIdRoute,
  AuthedWorkspaceIdTriggersTriggerIdRoute:
    AuthedWorkspaceIdTriggersTriggerIdRoute,
  AuthedWorkspaceIdAgentsIndexRoute: AuthedWorkspaceIdAgentsIndexRoute,
  AuthedWorkspaceIdObjectsIndexRoute: AuthedWorkspaceIdObjectsIndexRoute,
  AuthedWorkspaceIdTriggersIndexRoute: AuthedWorkspaceIdTriggersIndexRoute,
}

const AuthedWorkspaceIdRouteWithChildren =
  AuthedWorkspaceIdRoute._addFileChildren(AuthedWorkspaceIdRouteChildren)

interface AuthedRouteChildren {
  AuthedWorkspaceIdRoute: typeof AuthedWorkspaceIdRouteWithChildren
  AuthedWorkspacesRoute: typeof AuthedWorkspacesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedWorkspaceIdRoute: AuthedWorkspaceIdRouteWithChildren,
  AuthedWorkspacesRoute: AuthedWorkspacesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PrototypesAboveTitleHeaderRoute: PrototypesAboveTitleHeaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
