import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { useCallback } from 'react'
import {
	type ChangePasswordInput,
	type CreateActorInput,
	type LoginInput,
	type RequestEmailChangeInput,
	api,
} from '../lib/api'
import {
	clearAuth,
	getApiKey,
	getStoredActor,
	isAuthenticated,
	setApiKey,
	setStoredActor,
} from '../lib/auth'
import { queryKeys } from '../lib/query-keys'

export function useAuth() {
	const navigate = useNavigate()

	const login = useCallback(
		async (data: LoginInput) => {
			const result = await api.auth.login(data)
			setApiKey(result.api_key)
			setStoredActor({
				id: result.id,
				name: result.name,
				type: result.type,
				email: result.email,
			})
			navigate({ to: '/' })
			return result
		},
		[navigate],
	)

	const signup = useCallback(async (data: CreateActorInput) => {
		const result = await api.actors.create(data)
		setApiKey(result.api_key)
		setStoredActor({
			id: result.id,
			name: result.name,
			type: result.type,
			email: result.email,
		})
		return result
	}, [])

	const logout = useCallback(() => {
		clearAuth()
		navigate({ to: '/login' })
	}, [navigate])

	return {
		isAuthenticated: isAuthenticated(),
		apiKey: getApiKey(),
		actor: getStoredActor(),
		login,
		signup,
		logout,
	}
}

// Rotates the API key on success so the current tab keeps a working session.
// Per T1 contract: changing the password rotates the only credential — the
// response contains the new api_key and we swap it in immediately.
export function useChangePassword() {
	return useMutation({
		mutationFn: (data: ChangePasswordInput) => api.auth.changePassword(data),
		onSuccess: (result) => {
			setApiKey(result.api_key)
		},
	})
}

// Asks the backend to mint a verification token for `new_email`. The actor's
// `pending_email` flips to the target on success; the persistent banner in
// the profile page reads off that field and stays until verify or cancel
// clears it. We invalidate the cached actor so the banner appears immediately
// without waiting for an SSE refresh.
//
// `idempotencyKey` is a per-click UUID generated by the caller — a double-tap
// on Submit would otherwise mint two verification tokens.
export function useRequestEmailChange(actorId: string) {
	const queryClient = useQueryClient()
	return useMutation({
		mutationFn: ({
			data,
			idempotencyKey,
		}: { data: RequestEmailChangeInput; idempotencyKey?: string }) =>
			api.auth.requestEmailChange(data, idempotencyKey),
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: queryKeys.actors.detail(actorId) })
		},
	})
}

// Clears `pending_email` for the authenticated user. Used by the Cancel
// action on the verification banner. No body — the backend uses the auth'd
// actor id. Accepts a per-click `idempotencyKey` to keep a double-tap from
// running cancel twice.
export function useCancelEmailChange(actorId: string) {
	const queryClient = useQueryClient()
	return useMutation({
		mutationFn: ({ idempotencyKey }: { idempotencyKey?: string } = {}) =>
			api.auth.cancelEmailChange(idempotencyKey),
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: queryKeys.actors.detail(actorId) })
		},
	})
}
