import XCTest
@testable import Maskin

/// Golden values generated by running `hashString()` from
/// `apps/web/src/components/shared/actor-avatar.tsx` directly in Node — see the plan's
/// verification section: the ported Swift hash must stay bit-for-bit identical or the
/// same actor renders a different avatar color on iOS than on web.
final class ActorAvatarParityTests: XCTestCase {
	func testKnownSeedsMatchNodeReferenceIndex() {
		// (seed, expected `hash % 10` from the Node reference run)
		let cases: [(String, Int)] = [
			("actor-uuid-1234", 3),
			("Forge", 2),
			("?", 2),
			("a1b2c3d4-e5f6-7890-abcd-ef1234567890", 7),
			("Relay", 4),
		]
		for (seed, expectedIndex) in cases {
			XCTAssertEqual(ActorAvatarPalette.paletteIndex(seed: seed), expectedIndex, "seed=\(seed)")
		}
	}

	func testEmptySeedFallsBackToQuestionMark() {
		XCTAssertEqual(ActorAvatarPalette.paletteIndex(seed: ""), ActorAvatarPalette.paletteIndex(seed: "?"))
	}

	func testInitialsForTwoWordName() {
		XCTAssertEqual(ActorAvatarPalette.initials(name: "Ada Lovelace"), "AL")
	}

	func testInitialsForSingleWordName() {
		XCTAssertEqual(ActorAvatarPalette.initials(name: "Forge"), "FO")
	}

	func testInitialsForEmptyName() {
		XCTAssertEqual(ActorAvatarPalette.initials(name: ""), "?")
	}
}
