import type { Page } from '@playwright/test'
import { expect, test } from '../fixtures/auth.fixture'
import { TestAPI } from '../helpers/api.helper'
import { SHIP_GATE_VIEWPORTS } from '../helpers/viewports'

/**
 * Today's brief, as something a person listens to.
 *
 * The brief used to be the agent's own `WORKSPACE.md` read aloud — headings,
 * bullets, `id:` lines and a closing list of MCP tool names. It is now written
 * as prose by the workspace's default agent, and only when someone asks for
 * it: nothing is generated by loading the feed.
 *
 * These specs run against the real backend with no model credentials
 * configured, so the brief comes back through the deterministic fallback. That
 * is deliberate — the fallback is the floor, and every assertion here (prose,
 * no markup, on-demand) has to hold at the floor as well as above it.
 */

/**
 * Expand the card and reveal the prose. The brief leads with the player and
 * keeps the text folded away, so reading it is a second, deliberate click —
 * except where the browser cannot speak, in which case it is already open.
 */
async function openTranscript(page: Page) {
	const brief = page.getByTestId('brief-card')
	await brief.getByRole('button', { name: "Today's brief" }).click()
	const reveal = brief.getByRole('button', { name: /show the transcript/i })
	if (await reveal.isVisible().catch(() => false)) await reveal.click()
	return brief
}

const AGENT_ARTEFACTS = [
	/^#/m, // headings
	/^\s*-\s/m, // bullets
	/`/, // backticks
	/\*\*/, // bold
	/id:\s/, // the agent doc's id lines
	/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i,
]

test.describe("Today's brief — spoken prose, written on demand", () => {
	test('does not generate the brief until it is asked for', async ({ page, account }) => {
		let generateCalls = 0
		await page.route('**/api/briefing/spoken', async (route) => {
			generateCalls += 1
			await route.fallback()
		})

		await page.goto(`/${account.workspaceId}`)
		const brief = page.getByTestId('brief-card')
		await expect(brief).toBeVisible()
		await expect(brief.getByText(/tap to play/)).toBeVisible()

		// Loading the feed costs nothing.
		expect(generateCalls).toBe(0)

		await brief.getByRole('button', { name: "Today's brief" }).click()
		await expect.poll(() => generateCalls).toBe(1)
	})

	test('reads as prose, with none of the agent document in it', async ({ page, account }) => {
		const api = new TestAPI(account.apiKey)
		await api.createObject(account.workspaceId, {
			type: 'bet',
			title: 'Cut signup friction',
			status: 'active',
			content: 'Onboarding drops at the email step.',
		})

		await page.goto(`/${account.workspaceId}`)
		const brief = await openTranscript(page)

		const transcript = brief.getByTestId('brief-transcript')
		await expect(transcript).toBeVisible()
		const script = (await transcript.innerText()).trim()

		expect(script.length).toBeGreaterThan(0)
		for (const pattern of AGENT_ARTEFACTS) {
			expect(script).not.toMatch(pattern)
		}
		expect(script).not.toContain('Digging deeper')
		expect(script).not.toContain('get_objects')
		// Sentences, not a list — that is what gives the voice its pauses.
		expect(script).toMatch(/\.\s|\.$/)
	})

	test('serves the second ask from cache rather than rewriting', async ({ page, account }) => {
		await page.goto(`/${account.workspaceId}`)
		const first = await (await openTranscript(page)).getByTestId('brief-transcript').innerText()

		await page.reload()
		const second = await (await openTranscript(page)).getByTestId('brief-transcript').innerText()

		expect(second).toBe(first)
	})

	for (const vp of SHIP_GATE_VIEWPORTS) {
		test(`plays and reads at ${vp.label}`, async ({ page, account }) => {
			await page.setViewportSize({ width: vp.width, height: vp.height })
			await page.goto(`/${account.workspaceId}`)

			const brief = page.getByTestId('brief-card')
			await expect(brief).toBeVisible()

			// The play control is a real touch target, not a hover reveal.
			const play = brief.getByRole('button', { name: /read the brief aloud/i })
			await expect(play).toBeVisible()
			const box = await play.boundingBox()
			expect(box?.width ?? 0).toBeGreaterThanOrEqual(28)
			expect(box?.height ?? 0).toBeGreaterThanOrEqual(28)

			await brief.getByRole('button', { name: "Today's brief" }).click()
			await expect(brief.getByTestId('brief-player')).toBeVisible()

			// The card must never widen the page.
			const overflow = await page.evaluate(
				() => document.documentElement.scrollWidth - document.documentElement.clientWidth,
			)
			expect(overflow).toBeLessThanOrEqual(1)
		})
	}

	for (const scheme of ['light', 'dark'] as const) {
		test(`stays legible against the page in ${scheme} mode`, async ({ page, account }) => {
			await page.emulateMedia({ colorScheme: scheme })
			await page.goto(`/${account.workspaceId}`)

			const brief = page.getByTestId('brief-card')
			await expect(brief).toBeVisible()

			// The brief is the feed's one inverted surface — if it ever matched
			// the page background it would vanish (the bg-accent failure mode).
			const [cardBg, pageBg] = await Promise.all([
				brief.evaluate((el) => getComputedStyle(el).backgroundColor),
				page.evaluate(() => getComputedStyle(document.body).backgroundColor),
			])
			expect(cardBg).not.toBe(pageBg)

			await openTranscript(page)
			await expect(brief.getByTestId('brief-transcript')).toBeVisible()
		})
	}
})
